# Task 1



In [133]:
import pandas as pd
import numpy as np
df = pd.read_csv("Zadanie_1.csv",delimiter=";")
np_array = df.to_numpy()
np_array

array([[3.600000e+01, 2.700000e+01, 7.100000e+01, 8.100000e+00,
        3.340000e+00, 1.140000e+01, 8.150000e+01, 3.243000e+03,
        8.800000e+00, 4.260000e+01, 1.170000e+01, 2.100000e+01,
                 nan, 5.900000e+01, 5.900000e+01, 9.218700e+02],
       [3.500000e+01, 2.300000e+01, 7.200000e+01, 1.110000e+01,
        3.140000e+00, 1.100000e+01, 7.880000e+01, 4.281000e+03,
        3.600000e+00, 5.070000e+01, 1.440000e+01, 8.000000e+00,
        1.000000e+01, 3.900000e+01, 5.700000e+01, 9.978750e+02],
       [4.400000e+01, 2.900000e+01, 7.400000e+01, 1.040000e+01,
        3.210000e+00, 9.800000e+00, 8.160000e+01, 4.260000e+03,
        8.000000e-01, 3.940000e+01,          nan, 6.000000e+00,
        6.000000e+00, 3.300000e+01, 5.400000e+01, 9.623540e+02],
       [4.700000e+01, 4.500000e+01, 7.900000e+01, 6.500000e+00,
        3.410000e+00, 1.110000e+01, 7.750000e+01, 3.125000e+03,
        2.710000e+01, 5.020000e+01, 2.060000e+01, 1.800000e+01,
        8.000000e+00, 2.400000e+01, 5

In [134]:
np_array.size
print("Cells: ", np_array.size)
rows, cols = np_array.shape
print("Rows: ", rows)
print("Cols: ", cols)


def calculate_stats(np_array):

    print("Mean:", np.nanmean(np_array))
    print("Median:", np.nanmedian(np_array))
    print("Variance:", np.nanvar(np_array))

calculate_stats(np_array)

Cells:  960
Rows:  60
Cols:  16
Mean: 338.2209319148936
Median: 33.4
Variance: 1036473.5935947594


In [135]:
cleaned_np_array = np_array[~np.isnan(np_array).any(axis=1)]
calculate_stats(cleaned_np_array)

Mean: 332.2025610465116
Median: 34.0
Variance: 1042134.7488820893


# Task 2

In [136]:
matrix = pd.read_csv("Zadanie_2.csv", delimiter=";", header=None).to_numpy()
matrix

array([[  1,   2,  15, -59,   9,   3,  75,   6,   7,   1],
       [  0,   5,   0,   4,   6,  16,  44,   7,   1,   1],
       [  7,  14,   3, -10,   9,  15,  73,   8,   2,   9],
       [  1,   5,  15, -54,   5,  15,  35,   8,   6,   4],
       [  0,   8,   5, -18,   7,  16,  91,   6,   7,   9],
       [  7,  18,  23, -90,   4,   8,  31,   0,   1,   7],
       [  2,   8,  20, -72,   4,   1,  91,   9,   4,   4],
       [  4,  12,  18, -65,   6,   9,  76,   4,   9,   9],
       [  7,  15,  13, -52,   5,   7,  54,   2,   7,   0],
       [  2,   9,  15, -56,   6,   1,  98,   4,   8,   4]], dtype=int64)

In [137]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
inverse_matrix = np.linalg.inv(matrix)
print("Inverse matrix")
matrix

Eigenvalues: [104.34960192 +0.j         -23.35660516+18.84992811j
 -23.35660516-18.84992811j  15.92989017 +0.j
  -4.99456452 +0.j           0.35205717 +5.80125175j
   0.35205717 -5.80125175j  -1.03383491 +0.j
   3.87900166 +1.42651533j   3.87900166 -1.42651533j]
Eigenvectors:
 [[-0.29000475+0.j         -0.07545445+0.07743149j -0.07545445-0.07743149j
  -0.03544485+0.j          0.42681634+0.j         -0.22172831-0.29869259j
  -0.22172831+0.29869259j  0.41343726+0.j         -0.28670255+0.21891569j
  -0.28670255-0.21891569j]
 [-0.24163153+0.j          0.41229621+0.09197324j  0.41229621-0.09197324j
   0.45873475+0.j         -0.27056206+0.j         -0.01331344+0.1422557j
  -0.01331344-0.1422557j  -0.31591047+0.j          0.41954481-0.10561864j
   0.41954481+0.10561864j]
 [-0.41060573+0.j          0.37509638-0.00960818j  0.37509638+0.00960818j
   0.64067986+0.j         -0.37967609+0.j         -0.60525232+0.j
  -0.60525232-0.j          0.6457768 +0.j          0.63631555+0.j
   0.63631555-0.j  

array([[  1,   2,  15, -59,   9,   3,  75,   6,   7,   1],
       [  0,   5,   0,   4,   6,  16,  44,   7,   1,   1],
       [  7,  14,   3, -10,   9,  15,  73,   8,   2,   9],
       [  1,   5,  15, -54,   5,  15,  35,   8,   6,   4],
       [  0,   8,   5, -18,   7,  16,  91,   6,   7,   9],
       [  7,  18,  23, -90,   4,   8,  31,   0,   1,   7],
       [  2,   8,  20, -72,   4,   1,  91,   9,   4,   4],
       [  4,  12,  18, -65,   6,   9,  76,   4,   9,   9],
       [  7,  15,  13, -52,   5,   7,  54,   2,   7,   0],
       [  2,   9,  15, -56,   6,   1,  98,   4,   8,   4]], dtype=int64)

# Task 3

In [138]:
A = pd.read_csv("Zadanie_3_macierz_A.csv", header=None).to_numpy()
A

array([[2., 2., 3.],
       [1., 0., 4.],
       [6., 9., 7.]])

In [139]:
B = pd.read_csv("Zadanie_3_macierz_B.csv", header=None).to_numpy()
B

array([[ 1.,  5.,  2.],
       [ 6.,  6.,  4.],
       [ 1., 10.,  7.],
       [ 5.,  8.,  2.],
       [ 3.,  0.,  6.]])

In [140]:
import numpy as np

def cosine_similarity(A, B):
    dot_product = np.dot(A, B)
    norm_A = np.linalg.norm(A)
    norm_B = np.linalg.norm(B)
    cosine_sim = dot_product / (norm_A * norm_B)
    return cosine_sim

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

similarity = cosine_similarity(A, B)
print("Cosine Similarity:", similarity)

Cosine Similarity: 0.9746318461970762


In [141]:
def process_csv(file_path):
    df = pd.read_csv(file_path, header=None)
    return df.to_numpy()

matrix_a = process_csv('Zadanie_3_macierz_B.csv')
matrix_b = process_csv('Zadanie_3_macierz_B.csv')

def calculate_cosine_similarity_matrix(A, B):
    similarity_matrix = np.zeros((A.shape[0], B.shape[0]))

    for i in range(A.shape[0]):
        for j in range(B.shape[0]):
            vector_a = A[i, :]
            vector_b = B[j, :]

            dot_product = np.dot(vector_a, vector_b)

            norm_a = np.sqrt(np.sum(vector_a ** 2))
            norm_b = np.sqrt(np.sum(vector_b ** 2))
            similarity_matrix[i, j] = dot_product / (norm_a * norm_b)

    return similarity_matrix

result = calculate_cosine_similarity_matrix(matrix_a, matrix_b)

print("Cosine similarity matrix:")
print(np.round(result, 4))


Cosine similarity matrix:
[[1.     0.8563 0.969  0.9277 0.4082]
 [0.8563 1.     0.8182 0.9506 0.6674]
 [0.969  0.8182 1.     0.8382 0.5477]
 [0.9277 0.9506 0.8382 1.     0.4174]
 [0.4082 0.6674 0.5477 0.4174 1.    ]]


# Task 4

In [142]:
pd.set_option('display.max_rows', None)
df = pd.read_csv("Zadanie_4.csv", delimiter=";")
df

DateTime  DoctorID           Type    City  Unnamed: 4  \
0    16.03.2020 12:00         1             GP  Warsaw         NaN   
1    16.03.2020 12:01         1             GP  Warsaw         NaN   
2    16.03.2020 12:02         1             GP  Warsaw         NaN   
3    16.03.2020 12:03         1             GP  Warsaw         NaN   
4    16.03.2020 12:04         1             GP  Warsaw         NaN   
5    16.03.2020 12:05         1             GP  Warsaw         NaN   
6    16.03.2020 12:06         1             GP  Warsaw         NaN   
7    16.03.2020 12:07         1             GP  Warsaw         NaN   
8    16.03.2020 12:08         1             GP  Warsaw         NaN   
9    16.03.2020 12:09         1             GP  Warsaw         NaN   
10   16.03.2020 12:10         1             GP  Warsaw         NaN   
11   16.03.2020 12:11         1             GP  Warsaw         NaN   
12   16.03.2020 12:12         1             GP  Warsaw         NaN   
13   16.03.2020 12:13         1             GP  Warsaw         NaN   
14   16.03.2020 12:14         1             GP  Warsaw         NaN   
15   16.03.2020 12:15         1             GP  Warsaw         NaN   
16   16.03.2020 12:16         1             GP  Warsaw         NaN   
17   16.03.2020 12:00         2             GP  Krakow         NaN   
18   16.03.2020 12:01         2             GP  Krakow         NaN   
19   16.03.2020 12:02         2             GP  Krakow         NaN   
20   16.03.2020 12:03         2             GP  Krakow         NaN   
21   16.03.2020 12:04         2             GP  Krakow         NaN   
22   16.03.2020 12:05         2             GP  Krakow         NaN   
23   16.03.2020 12:06         2             GP  Krakow         NaN   
24   16.03.2020 12:07         2             GP  Krakow         NaN   
25   16.03.2020 12:08         2             GP  Krakow         NaN   
26   16.03.2020 12:09         2             GP  Krakow         NaN   
27   16.03.2020 12:10         2             GP  Krakow         NaN   
28   16.03.2020 12:11         2             GP  Krakow         NaN   
29   16.03.2020 12:12         2             GP  Krakow         NaN   
30   16.03.2020 12:13         2             GP  Krakow         NaN   
31   16.03.2020 12:14         2             GP  Krakow         NaN   
32   16.03.2020 12:15         2             GP  Krakow         NaN   
33   16.03.2020 12:16         2             GP  Krakow         NaN   
34   16.03.2020 12:17         2             GP  Krakow         NaN   
35   16.03.2020 12:18         2             GP  Krakow         NaN   
36   16.03.2020 12:19         2             GP  Krakow         NaN   
37   16.03.2020 12:20         2             GP  Krakow         NaN   
38   16.03.2020 12:21         2             GP  Krakow         NaN   
39   16.03.2020 12:22         2             GP  Krakow         NaN   
40   16.03.2020 12:23         2             GP  Krakow         NaN   
41   16.03.2020 12:24         2             GP  Krakow         NaN   
42   16.03.2020 12:25         2             GP  Krakow         NaN   
43   16.03.2020 12:26         2             GP  Krakow         NaN   
44   16.03.2020 12:27         2             GP  Krakow         NaN   
45   16.03.2020 12:28         2             GP  Krakow         NaN   
46   16.03.2020 12:29         2             GP  Krakow         NaN   
47   16.03.2020 12:30         2             GP  Krakow         NaN   
48   16.03.2020 12:31         2             GP  Krakow         NaN   
49   16.03.2020 12:32         2             GP  Krakow         NaN   
50   16.03.2020 12:33         2             GP  Krakow         NaN   
51   16.03.2020 12:34         2             GP  Krakow         NaN   
52   16.03.2020 12:35         2             GP  Krakow         NaN   
53   16.03.2020 12:36         2             GP  Krakow         NaN   
54   16.03.2020 12:37         2             GP  Krakow         NaN   
55   16.03.2020 12:38         2             GP  Krakow         NaN   
56   16.03.2020 12:39  

In [143]:
import pandas as pd

df['DateTime'] = pd.to_datetime(df['DateTime'], format='%d.%m.%Y %H:%M')
df.sort_values(by=['DoctorID', 'DateTime'], inplace=True)

df['Time_Diff'] = df.groupby(['DoctorID'])['DateTime'].diff().dt.seconds.div(60).fillna(1)

df['Group'] = (df['Time_Diff'] > 1).cumsum()

df = df.groupby(['DoctorID', 'Type', 'City', 'Group']).agg(
    Start=('DateTime', 'first'),
    End=('DateTime', 'last')
).reset_index()

print(df)
df.info()



   DoctorID           Type    City  Group               Start  \
0         1             GP  Warsaw      0 2020-03-16 12:00:00   
1         1             GP  Warsaw      1 2020-03-16 13:49:00   
2         1             GP  Warsaw      2 2020-03-29 14:00:00   
3         2             GP  Krakow      2 2020-03-16 12:00:00   
4         3        Sugreon  Warsaw      2 2020-03-22 08:01:00   
5         4  Opthomologist  Krakow      2 2020-04-10 13:20:00   

                  End  
0 2020-03-16 12:16:00  
1 2020-03-16 14:01:00  
2 2020-03-29 14:37:00  
3 2020-03-16 12:49:00  
4 2020-03-22 09:06:00  
5 2020-04-10 13:34:00  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   DoctorID  6 non-null      int64         
 1   Type      6 non-null      object        
 2   City      6 non-null      object        
 3   Group     6 non-null      int32         


In [ ]:
df.to_csv('doctor_availability', index=False)